"""m13_company_employment

Revision ID: 01f352fee948
Revises: 7a8901c4ba15
Create Date: 2026-08-06 14:35:08.674268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f352fee948'
down_revision: Union[str, Sequence[str], None] = '7a8901c4ba15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_inventories',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('world_id', 'company_id', 'item_id')
    )
    op.create_table('company_transactions',
    sa.Column('transaction_id', sa.String(length=48), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('related_agent_id', sa.String(length=64), nullable=True),
    sa.Column('related_item_id', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=32), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('world_time', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('ix_company_transactions_world_company', 'company_transactions', ['world_id', 'company_id'], unique=False)
    op.create_table('employment_contracts',
    sa.Column('employment_id', sa.String(length=48), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('position_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('hired_at', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Integer(), nullable=False),
    sa.Column('ended_at', sa.Integer(), nullable=True),
    sa.Column('wage_per_shift', sa.Integer(), nullable=False),
    sa.Column('attendance_score', sa.Float(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('completed_shifts', sa.Integer(), nullable=False),
    sa.Column('late_shifts', sa.Integer(), nullable=False),
    sa.Column('absent_shifts', sa.Integer(), nullable=False),
    sa.Column('unpaid_wage', sa.Integer(), nullable=False),
    sa.Column('termination_reason', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('employment_id')
    )
    op.create_index('ix_employment_contracts_world_agent_status', 'employment_contracts', ['world_id', 'agent_id', 'status'], unique=False)
    op.create_table('job_applications',
    sa.Column('application_id', sa.String(length=48), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('opening_id', sa.String(length=48), nullable=False),
    sa.Column('position_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('applied_at', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_agent_id', sa.String(length=64), nullable=True),
    sa.Column('applicant_reason', sa.String(length=512), nullable=False),
    sa.Column('manager_reason', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index('ix_job_applications_world_company_status', 'job_applications', ['world_id', 'company_id', 'status'], unique=False)
    # R24: one ACTIVE application per (opening, agent) — withdrawn/rejected
    # rows free the slot so the resident can re-apply (SQLite partial index).
    op.create_index('uq_job_application_active_opening_agent', 'job_applications', ['world_id', 'opening_id', 'agent_id'], unique=True, sqlite_where=sa.text("status IN ('submitted', 'reviewing')"))
    op.create_table('work_shifts',
    sa.Column('shift_id', sa.String(length=48), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('employment_id', sa.String(length=48), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('position_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('scheduled_start', sa.Integer(), nullable=False),
    sa.Column('scheduled_end', sa.Integer(), nullable=False),
    sa.Column('actual_start', sa.Integer(), nullable=True),
    sa.Column('actual_end', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('worked_minutes', sa.Integer(), nullable=False),
    sa.Column('wage_due', sa.Integer(), nullable=False),
    sa.Column('wage_paid', sa.Integer(), nullable=False),
    sa.Column('payroll_status', sa.String(length=24), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('absence_reason', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('shift_id'),
    sa.UniqueConstraint('world_id', 'employment_id', 'scheduled_start', name='uq_work_shift_contract_start')
    )
    op.create_index('ix_work_shifts_world_agent_status', 'work_shifts', ['world_id', 'agent_id', 'status'], unique=False)
    op.create_table('leave_requests',
    sa.Column('request_id', sa.String(length=48), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('shift_id', sa.String(length=64), nullable=False),
    sa.Column('employment_id', sa.String(length=48), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('manager_reason', sa.String(length=512), nullable=True),
    sa.Column('requested_at', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_agent_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('ix_leave_requests_world_company_status', 'leave_requests', ['world_id', 'company_id', 'status'], unique=False)
    op.create_index('ix_leave_requests_world_shift', 'leave_requests', ['world_id', 'shift_id'], unique=False)
    op.create_table('companies',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('company_type', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.Column('owner_agent_id', sa.String(length=64), nullable=True),
    sa.Column('manager_agent_id', sa.String(length=64), nullable=True),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('founded_at', sa.Integer(), nullable=False),
    sa.Column('suspended_at', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.Integer(), nullable=True),
    sa.Column('consecutive_loss_days', sa.Integer(), nullable=False),
    sa.Column('unpaid_wage_total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'company_id')
    )
    op.create_table('positions',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('position_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('wage_per_shift', sa.Integer(), nullable=False),
    sa.Column('shift_start_minute', sa.Integer(), nullable=False),
    sa.Column('shift_end_minute', sa.Integer(), nullable=False),
    sa.Column('working_days_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['world_id', 'company_id'], ['companies.world_id', 'companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'position_id')
    )
    op.create_table('job_openings',
    sa.Column('opening_id', sa.String(length=48), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('position_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('opened_at', sa.Integer(), nullable=False),
    sa.Column('closes_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['world_id', 'position_id'], ['positions.world_id', 'positions.position_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opening_id')
    )
    op.create_index(op.f('ix_job_openings_world_id'), 'job_openings', ['world_id'], unique=False)
    op.add_column('stores', sa.Column('company_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'company_id')
    op.drop_index(op.f('ix_job_openings_world_id'), table_name='job_openings')
    op.drop_table('job_openings')
    op.drop_table('positions')
    op.drop_table('companies')
    op.drop_index('ix_work_shifts_world_agent_status', table_name='work_shifts')
    op.drop_table('work_shifts')
    op.drop_index('ix_leave_requests_world_company_status', table_name='leave_requests')
    op.drop_index('ix_leave_requests_world_shift', table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index('uq_job_application_active_opening_agent', table_name='job_applications')
    op.drop_index('ix_job_applications_world_company_status', table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index('ix_employment_contracts_world_agent_status', table_name='employment_contracts')
    op.drop_table('employment_contracts')
    op.drop_index('ix_company_transactions_world_company', table_name='company_transactions')
    op.drop_table('company_transactions')
    op.drop_table('company_inventories')
    # ### end Alembic commands ###
