"""m7_god

Revision ID: 3cf9f98ff681
Revises: 896089c8c576
Create Date: 2026-08-05 15:49:29.677854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf9f98ff681'
down_revision: Union[str, Sequence[str], None] = '896089c8c576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('god_actions',
    sa.Column('command_id', sa.String(length=64), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('command_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('command_id')
    )
    op.create_index('ix_god_actions_world_created', 'god_actions', ['world_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_god_actions_world_created', table_name='god_actions')
    op.drop_table('god_actions')
    # ### end Alembic commands ###
