"""m4_conversations

Revision ID: 86dd1705b9db
Revises: b3d85d11f599
Create Date: 2026-08-05 13:53:26.066924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86dd1705b9db'
down_revision: Union[str, Sequence[str], None] = 'b3d85d11f599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('agent_a', sa.String(length=64), nullable=False),
    sa.Column('agent_b', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.Integer(), nullable=False),
    sa.Column('ended_at', sa.Integer(), nullable=True),
    sa.Column('end_reason', sa.String(length=32), nullable=True),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index('ix_conversations_world_agent_a', 'conversations', ['world_id', 'agent_a'], unique=False)
    op.create_index('ix_conversations_world_agent_b', 'conversations', ['world_id', 'agent_b'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('from_agent_id', sa.String(length=64), nullable=False),
    sa.Column('to_agent_id', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.Column('intent', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.Integer(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_conversation_messages_conversation_id', 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index('ix_conversation_messages_to_read', 'conversation_messages', ['to_agent_id', 'read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversation_messages_to_read', table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_conversation_id', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('ix_conversations_world_agent_b', table_name='conversations')
    op.drop_index('ix_conversations_world_agent_a', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
