"""m2_world_engine

Revision ID: 895e7abfefe7
Revises: 6a282ff85764
Create Date: 2026-08-04 20:50:06.218628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895e7abfefe7'
down_revision: Union[str, Sequence[str], None] = '6a282ff85764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worlds',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('world_time', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('weather', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('world_id')
    )
    op.create_table('agents',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(length=64), nullable=False),
    sa.Column('background', sa.String(length=512), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('long_term_goals', sa.JSON(), nullable=False),
    sa.Column('speaking_style', sa.String(length=128), nullable=False),
    sa.Column('personality', sa.JSON(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=True),
    sa.Column('hunger', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=True),
    sa.Column('action_started_at', sa.Integer(), nullable=True),
    sa.Column('action_ends_at', sa.Integer(), nullable=True),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'agent_id')
    )
    op.create_table('locations',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location_type', sa.String(length=32), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('open_hour', sa.Integer(), nullable=False),
    sa.Column('close_hour', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'location_id')
    )
    op.create_table('scheduled_actions',
    sa.Column('action_id', sa.String(length=48), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index('ix_scheduled_world_due', 'scheduled_actions', ['world_id', 'due_at'], unique=False)
    op.create_table('world_events',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('world_time', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'event_id'),
    sa.UniqueConstraint('world_id', 'sequence', name='uq_world_events_world_sequence')
    )
    op.create_index('ix_world_events_world_seq', 'world_events', ['world_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_world_events_world_seq', table_name='world_events')
    op.drop_table('world_events')
    op.drop_index('ix_scheduled_world_due', table_name='scheduled_actions')
    op.drop_table('scheduled_actions')
    op.drop_table('locations')
    op.drop_table('agents')
    op.drop_table('worlds')
    # ### end Alembic commands ###
