"""m6_memories

Revision ID: 896089c8c576
Revises: 9186b35dda30
Create Date: 2026-08-05 15:30:16.194271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896089c8c576'
down_revision: Union[str, Sequence[str], None] = '9186b35dda30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('memory_type', sa.String(length=16), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('entities_json', sa.JSON(), nullable=False),
    sa.Column('keywords_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('last_recalled_at', sa.Integer(), nullable=True),
    sa.Column('recall_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index('ix_memories_world_agent', 'memories', ['world_id', 'agent_id'], unique=False)
    op.create_table('relationships',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('source_agent_id', sa.String(length=64), nullable=False),
    sa.Column('target_agent_id', sa.String(length=64), nullable=False),
    sa.Column('familiarity', sa.Integer(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('affection', sa.Integer(), nullable=False),
    sa.Column('resentment', sa.Integer(), nullable=False),
    sa.Column('debt', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'source_agent_id', 'target_agent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    op.drop_index('ix_memories_world_agent', table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
