"""m5_economy

Revision ID: 9186b35dda30
Revises: 86dd1705b9db
Create Date: 2026-08-05 14:53:09.082259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9186b35dda30'
down_revision: Union[str, Sequence[str], None] = '86dd1705b9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('hunger_restore', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'item_id')
    )
    op.create_table('jobs',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.Column('interactable_id', sa.String(length=64), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('wage', sa.Integer(), nullable=False),
    sa.Column('energy_cost_per_hour', sa.Integer(), nullable=False),
    sa.Column('products_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'job_id')
    )
    op.create_table('stores',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'store_id')
    )
    op.create_table('transactions',
    sa.Column('tx_id', sa.String(length=48), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('world_time', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tx_id')
    )
    op.create_index('ix_transactions_world_agent', 'transactions', ['world_id', 'agent_id'], unique=False)
    op.create_table('employments',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id', 'agent_id'], ['agents.world_id', 'agents.agent_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id', 'job_id'], ['jobs.world_id', 'jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'agent_id', 'job_id')
    )
    op.create_table('inventories',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id', 'agent_id'], ['agents.world_id', 'agents.agent_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id', 'item_id'], ['items.world_id', 'items.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'agent_id', 'item_id')
    )
    op.create_table('store_products',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('sell_price', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('stock_cap', sa.Integer(), nullable=False),
    sa.Column('restock_daily', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id', 'item_id'], ['items.world_id', 'items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id', 'store_id'], ['stores.world_id', 'stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'store_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_products')
    op.drop_table('inventories')
    op.drop_table('employments')
    op.drop_index('ix_transactions_world_agent', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('stores')
    op.drop_table('jobs')
    op.drop_table('items')
    # ### end Alembic commands ###
