"""m3_llm_agents

Revision ID: b3d85d11f599
Revises: 895e7abfefe7
Create Date: 2026-08-05 13:28:40.798435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d85d11f599'
down_revision: Union[str, Sequence[str], None] = '895e7abfefe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_runs',
    sa.Column('run_id', sa.String(length=48), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('world_time', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=32), nullable=False),
    sa.Column('tool_arguments', sa.JSON(), nullable=False),
    sa.Column('tool_result', sa.JSON(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('raw_summary', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.world_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('ix_llm_runs_world_agent', 'llm_runs', ['world_id', 'agent_id'], unique=False)
    op.add_column('agents', sa.Column('is_deciding', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('agents', sa.Column('consecutive_failures', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('worlds', sa.Column('autonomous', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worlds', 'autonomous')
    op.drop_column('agents', 'consecutive_failures')
    op.drop_column('agents', 'is_deciding')
    op.drop_index('ix_llm_runs_world_agent', table_name='llm_runs')
    op.drop_table('llm_runs')
    # ### end Alembic commands ###
